sudo: false
language: rust
rust:
- nightly
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - cmake
    - gcc
    - binutils-dev
    sources:
    - kalakris-cmake
before_script:
- cargo install cargo-travis && export PATH=$HOME/.cargo/bin:$PATH
script:
- cargo build --verbose
- cargo test --verbose
- cargo bench --verbose
- cargo doc --verbose
after_success:
- cargo coveralls
notifications:
  slack:
    secure: azjU1WDGOBROC149UsdcNiac95KfNr6SbCjGU9xlryinaILEMWwH8HhoQXGZbPt2tojZffRq94SythSMnMSEsFh2LYcJxK+w+hAM8bNQj5POWxjC7ds6TGE/T0E7a4IbYzuu9ig+RG7IqSyTWxQlXveOh9U146j3VQ6Z8bqvttKjlbTmFCDQYedx0DRwlZAe7r1qV8YqTlr959Sup/9jx/Yq282iiWt0XfO9NRYck7ZH5aKuU2dhotACCKBjM9IPMOtrkmmRGnB5iKVGieRjB8gha2y4rdsyIjRsY0UgwkwZ9IaBrft+cWxV5mUFYo7TiOXoAVqBOt6s/Vvaj5If6xVdj2DvO4YUMAZ040CH6CmoATS8gA6D+Q9FoYXS/qjswlsLsZIh7C/FV+oFePrDw5zBeTPnazdpamjREM5VG/dgPIdeQ1YFhjOC8BHplMgSBVWOLewmjmBZLH9WINEG2rlIBN9Xhbi/zSbFositUvjTfC/wdfFLVYWeQuNbiprF8OzhHwgJRjVl0O4mPq7CnGlRsGo5hJeUcaJw57px2GQsFzLnTgG1iUnRUxPmrRgcarHGaUMh8hNUd/fB7rhm/kbev+W86RKltGn9YD5cCew7yvUQVPhErlLyxXF+8BIl2+YfOyeWOLbdnk2Ad7O72jgYnNUOsDV3UppX9gVFQCE=
